### ISSUE TITLE
ConfigParser not found

### ISSUE THREAD

**Issue by JamesMackerel** [python-beaver/python-conf_d#6]
ConfigParse has changed to  configparser in Python3, when install Beaver from pip, the problem occurs and leads the installation to failure.

**Comment by JamesMackerel** [comment]
I changed
```python 
import ConfigParser
```
to
```python
try:
    import ConfigParser
except ImportError:
    import configparser as ConfigParser
```

The installation seems no problem, but I don't know if they have changed the interfaces. Please update the setup packages in PyPi, Thank you!

**Comment by josegonzalez** [comment]
I have never tested this on python 3 and have no desire to do so locally. Feel free to make a pull request to this project so I can merge/release. Thanks.

**Comment by xavierhardy** [comment]
As @josegonzalez mentioned, it's a compatibility issue. #7 should fix it. I have also added support for Tox to avoid this kind of issue in the future.
